FROM node:22-alpine

WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Copy application files
COPY . .

EXPOSE 3000

ENV NODE_ENV development
ENV NEXT_TELEMETRY_DISABLED 1

CMD ["npm", "run", "dev"]
